### ISSUE TITLE
Missing 'LIVE_Livestream_trained_svr.z'

### ISSUE THREAD

**Issue by AdrienSchadle** [JoshuaEbenezer/ChipQA#1]
Hi,

I try to use ChipQA to evaluate the quality of a sequence and I failed. Can you tell me what is wrong in my following steps:
1 - I get a "feature" file after the command 
python.exe chipqa_yuv.py --input_file file.yuv --results_file .\result --width 1920 --height 1080 --bit_depth 8 --color_space BT709
2 - I run 
python zip_feat_and_scores.py chipqa_apv_features apv_livestream_scores.csv ai
3 - I run
python svr.py ai
4 - I run
python testing.py result.

Last step failed with the error "FileNotFoundError: [Errno 2] No such file or directory: 'LIVE_Livestream_trained_svr.z'"

When I check the code, to produce 'LIVE_Livestream_trained_svr.z', I need to run svr.py with the variable dataset to "onlytrain". But if I apply this change I have another error.

Can you tell me how I can use your software to evaluate my YUV sequence ?

Thanks in advance,
Adrien

**Comment by JoshuaEbenezer** [comment]
Hi Adrien
Sorry for the late reply! Was away on holidays. The paths were incorrect in the testing file because I had renamed the SVR and scaler in an earlier commit. I have corrected the names and it should work now. 
Also, you should only use the pretrained SVR for high-motion content with livestreaming distortions. NR VQA algorithms are sensitive to the training data, so please don't use pretrained ChipQA on videos/distortions that are fundamentally different from the LIVE Livestream database.
Regards
Josh

**Comment by AdrienSchadle** [comment]
Hi Joshua,

Thanks for your fix. It seems ok, I have some "UserWarning", but a result is displayed like this:
[[-0.84618649 -0.60306502  0.52308485  0.18188258 -0.62120759 -0.75023512
   0.5322167  -0.20463394 -0.96750196 -0.31124152 -0.13580182 -0.43575298
  -0.91481629 -0.14484917 -0.24968453 -0.50764022 -0.83022951 -0.46408739
  -0.32862301 -0.73079545 -0.79456906 -0.24687619 -0.31606117 -0.80355035
  -0.78997632 -0.05081031 -0.49042876 -0.76806047 -0.78844066 -0.36481286
  -0.39329045 -0.80454494 -0.81812832 -0.38468941 -0.47140043 -0.60318257
  -0.7516182  -0.34298898 -0.3872608  -0.74785484 -0.75589538  0.24387818
  -0.47939146 -0.63868433 -0.75560265 -0.33545987 -0.47518283 -0.6544943
  -0.95122185 -0.07618151 -0.27405805 -0.68853121 -0.85095535 -0.07337402
  -0.19404676 -0.51783767 -0.9965864  -0.96346528 -0.95524467 -0.96264607
  -0.98208494 -0.96110377 -0.93247086 -0.91522825 -0.98869843 -0.94269655
  -0.90900572 -0.91273115 -0.98900088 -0.95938564 -0.933854   -0.95986071
  -0.9891106  -0.97240072 -0.96613525 -0.98634898 -0.99000914 -0.97798249
  -0.98345251 -0.98351801 -0.98791749 -0.98331423 -0.98453244 -0.98936118
  -0.9887162  -0.97442304 -0.98711102 -0.9859964  -0.98923407 -0.96680046
  -0.95565594 -0.97320993 -0.9855959  -0.9748113  -0.96427782 -0.98169022
  -0.9871117  -0.97819184 -0.9742451  -0.98375    -0.98591837 -0.96944957
  -0.96665142 -0.98345135 -0.99042581 -0.96788706 -0.98737243 -0.99237636
  -0.9847122  -0.96847811 -0.97643042 -0.99148643 -0.82973858 -0.52169917
  -0.9344327  -0.28524247 -0.86045806 -0.87484266 -0.93152472  0.46880416
  -0.89414189 -0.81972883 -0.91427336  0.28701843 -0.84866797 -0.80677291
  -0.91424699  0.30408981 -0.84850168 -0.80642116 -0.80045142 -0.43480764
  -0.90700304  0.55005881 -0.75383294 -0.84770806 -0.91699566  0.03226626
  -0.9159498  -0.7555652  -0.89581257  0.64122891 -0.81873736 -0.75434072
  -0.89967796  0.63781478 -0.82228131 -0.74946295 -0.95919032 -0.84160566
  -0.58915856 -0.71463    -0.08929072 -0.94878494 -0.92238274 -0.72279796
  -0.80651556 -0.94121503 -0.9355315  -0.745628    0.06416492 -0.93129241
  -0.93887607 -0.74944596  0.19857976 -0.93565336 -0.93313551 -0.84743087
  -0.37894676 -0.71974969 -0.47692944 -0.72189776 -0.81944841 -0.72816824
  -0.71429164 -0.78979984 -0.73795039 -0.76429388 -0.54966019 -0.74804535
  -0.78600228 -0.76634751 -0.30148153 -0.75960175 -0.77236573 -0.72497218
  -0.43437821 -0.50927474 -0.25675451 -0.44894838 -0.64950496 -0.51114199
  -0.56420276 -0.58523371 -0.83059556 -0.54607629  0.16625552 -0.59270641
  -0.64555281 -0.54781333  0.25004437 -0.59854639 -0.63196296 -0.70641177
  -0.23101339 -0.5090039  -0.26039287 -0.25838517 -0.47072416 -0.49768533
  -0.34857569 -0.65308162 -0.66535237 -0.5501871   0.32426811 -0.36923338
  -0.44310346 -0.54835147  0.53721688 -0.39803596 -0.41504993]]
[50.54142667]

Sorry for my naive question, but is the last number ("50.54142667") the video quality prediction (like a MOS) ? Is a value between 0 and 100 ? Thanks a lot.

Regards
Adrien

**Comment by JoshuaEbenezer** [comment]
Not a naive question! 50.5414 is indeed the predicted score. The first array that is printed is the feature file. This is a messy output so I've cleaned up the testing code in the latest commit to print out only the predicted score with a statement that it is the predicted score.

**Comment by AdrienSchadle** [comment]
Thanks a lot. Last question and I close the issue, has predicted score a maximum value ? It's just to know if a predicted score is good or not.

**Comment by JoshuaEbenezer** [comment]
No there's no maximum value because the SVR output has no bounds imposed.
The scores the SVR was trained on had a maximum value of 100, however.

**Comment by AdrienSchadle** [comment]
Sorry for the late reply and thank you for the information
